// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReviewsSite;

namespace ReviewsSite.Migrations
{
    [DbContext(typeof(RecordStoreContext))]
    [Migration("20210302211607_MikesAlbums")]
    partial class MikesAlbums
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ReviewsSite.Models.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BandName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SongsString")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Albums");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BandName = "Metallica",
                            Description = "Is the fifth studio album by American heavy metal band Metallica, released on August 12, 1991 through Elektra Records.It was recorded in an eight - month span at One on One Recording Studios in Los Angeles.",
                            Image = "Images/Metallica-Black-Album.jpg",
                            Name = "The Black Album",
                            SongsString = "Enter Sandman, Sad But True, Holier Than Thou, The Unforgiven, Wherever I May Roam, Don't Tread on Me, Through the Never, Nothing Else Matters, Of Wolf and Man, The God That Failed, My Friend of Misery, The Struggle Within"
                        },
                        new
                        {
                            Id = 2,
                            BandName = "Kid Cudi",
                            Description = "Is the seventh studio album by American rapper Kid Cudi. It was released on December 11, 2020 by Republic Records. It is the final installment of Cudi's Man on the Moon trilogy of albums.",
                            Image = "Images/Man_on_the_Moon_III.jpg",
                            Name = "Man on the Moon 3",
                            SongsString = "Beautiful Trip, Tequila Shots, Another Day, She Knows This, Dive, Damaged, Heaven On Earth, Show Out, Solo Dolo, Pt. III, Sad People, Elsie's Baby Boy (flashback), Sept. 16, The Void, Lovin' Me, The Pale Moonlight, Rockstar Knights, 4 Da Kidz, Lord I Know"
                        },
                        new
                        {
                            Id = 3,
                            BandName = "Biggie Smalls",
                            Description = "Ready to Die is the debut studio album by American rapper The Notorious B.I.G., released on September 13, 1994, by Bad Boy Records and Arista Records. The album features productions by Yung Chedder (James Ryan), Bad Boy founder Sean Puffy Combs, Easy Mo Bee, Chucky Thompson, DJ Premier, and Lord Finesse, among others. It was recorded from 1993 to 1994 at The Hit Factory and D&D Studios in New York City",
                            Image = "Images/2nd album.jpg",
                            Name = "Ready To Die",
                            SongsString = "Intro, The What, Unbelievable, Things Done Changed, Juicy, One more chance, Warning, Everyday Struggle, Respect, Suicidal Thoughts, Friend of Me, Gimme the Loot, Machine Gun Funk,Ready To Die, Me & My Bitch, Big Poppa, F*ck Me, Just Playing, Who Shot Ya, Warning, Friend of Mine "
                        },
                        new
                        {
                            Id = 4,
                            BandName = "Apashe",
                            Description = "Publishied on Febuary 28 2018 Apashe lines one up for the home team as he drops his largest release on Kannibalen Records yet. A conceptual project that combines his usual love of hip-hop-infused bass with the orchestral influences of Mozart, the aptly titled Requiem project brings on the dancefloor heat while also smashing it on the production tip—from recording live instruments in cavernous churches to controlling the mixing and mastering of the EP with his untouchable ear. Expect to hear plenty of the three tracks being dropped alongside label mates Black Tiger Sex Machine as they embark on their otherworldly Ceremony Tour.",
                            Image = "Images/1st album.jpg",
                            Name = "Requiem",
                            SongsString = "Majesty feat. Wasiu (feat. Wasiu), Dies Irae feat. Black Prez (feat. Black Prez), Lacrimosa"
                        },
                        new
                        {
                            Id = 5,
                            BandName = "Saves the Day",
                            Description = "Through Being Cool is the second studio album by American rock band Saves the Day, released on November 2, 1999 by Equal Vision. The songs on Through Being Cool were written while the band members attended New York University. The album was recorded in 11 days and represented the band's transition from a melodic hardcore sound to a more pop punk style. It was produced by Steve Evetts at Trax East Recording Studio in South River, New Jersey.",
                            Image = "Images/STD TBC.jpg",
                            Name = "Through Being Cool",
                            SongsString = "All-Star Me, You Vandal, Shoulder to the Wheel, Rocks Tonic Juice Magic, Holly Hox Forget Me Nots, Third Engine, My Sweet Fracture, The Vast Spoils of America (From the Badlands through the Ocean), The Last Lie I Told, Do You Know What I Love the Most?, Through Being Cool, Banned from the Back Porch"
                        },
                        new
                        {
                            Id = 6,
                            BandName = "Weezer",
                            Description = "Pinkerton is the second studio album by American rock band Weezer, released on September 24, 1996 by DGC Records. After abandoning plans for a rock opera entitled Songs from the Black Hole, Weezer recorded the album between songwriter Rivers Cuomo's terms at Harvard University, where he wrote most of the songs.",
                            Image = "Images/WP.jpg",
                            Name = "Pinkerton",
                            SongsString = "Tired of Sex, Getchoo, No Other One, Why Bother?, Across the Sea, The Good Life, El Scorcho, Pink Triangle, Falling for You, Butterfly"
                        });
                });

            modelBuilder.Entity("ReviewsSite.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AlbumId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("ReviewerName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlbumId = 1,
                            Content = "Man this Album blew my mind",
                            Rating = 2,
                            ReviewerName = "AL Might"
                        },
                        new
                        {
                            Id = 2,
                            AlbumId = 2,
                            Content = "Man this is the best version of Cudi",
                            Rating = 2,
                            ReviewerName = "Mob"
                        },
                        new
                        {
                            Id = 3,
                            AlbumId = 3,
                            Content = "Best of its time",
                            Rating = 5,
                            ReviewerName = "Karen"
                        },
                        new
                        {
                            Id = 4,
                            AlbumId = 4,
                            Content = "Mightest three song album of It's genre",
                            Rating = 5,
                            ReviewerName = "Bruce Wayne"
                        },
                        new
                        {
                            Id = 5,
                            AlbumId = 5,
                            Content = "I'm so proud of my boy! He worked so hard and did such a good job!",
                            Rating = 5,
                            ReviewerName = "Chris Conley's mom"
                        },
                        new
                        {
                            Id = 6,
                            AlbumId = 5,
                            Content = "Lol, you listen to pop punk?",
                            Rating = 1,
                            ReviewerName = "Jake Ebinger"
                        },
                        new
                        {
                            Id = 7,
                            AlbumId = 6,
                            Content = "I Love this album! I listen to it while I'm cryogenically frozen between Christmas'.",
                            Rating = 4,
                            ReviewerName = "Michael Buble"
                        },
                        new
                        {
                            Id = 8,
                            AlbumId = 6,
                            Content = "Such a good album. You have to check it out!",
                            Rating = 5,
                            ReviewerName = "Jeremy Leuenberger"
                        },
                        new
                        {
                            Id = 9,
                            AlbumId = 6,
                            Content = "This was their last good album.",
                            Rating = 5,
                            ReviewerName = "Every Weezer Fan Ever"
                        });
                });

            modelBuilder.Entity("ReviewsSite.Models.Review", b =>
                {
                    b.HasOne("ReviewsSite.Models.Album", "Album")
                        .WithMany("Review")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");
                });

            modelBuilder.Entity("ReviewsSite.Models.Album", b =>
                {
                    b.Navigation("Review");
                });
#pragma warning restore 612, 618
        }
    }
}
